### ISSUE TITLE
nameof() expressions have no distinct exported tree-node, but are instead reported as invocation_expressions 

### ISSUE THREAD

**Issue by josteink** [tree-sitter/tree-sitter-c-sharp#242]
Consider the following C# code:

````c#
public class Demo
{
    public void Main()
    {
        var foo = typeof(bar);
    }
}
````

In this case, the resulting tree-sitter looks like this:

````
compilation_unit:
  class_declaration:
    modifier:
    identifier:
    declaration_list:
      method_declaration:
        modifier:
        void_keyword:
        identifier:
        parameter_list:
        block:
          local_declaration_statement:
            variable_declaration:
              implicit_type:
              variable_declarator:
                identifier:
                equals_value_clause:
                  type_of_expression:
                    identifier:
```` 

Similarly I would expect a `name_of_expression` for the following code:

````c#
public class Demo
{
    public void Main()
    {
        var foo = nameof(bar);
    }
}
````

Instead we get this:

````
compilation_unit:
  class_declaration:
    modifier:
    identifier:
    declaration_list:
      method_declaration:
        modifier:
        void_keyword:
        identifier:
        parameter_list:
        block:
          local_declaration_statement:
            variable_declaration:
              implicit_type:
              variable_declarator:
                identifier:
                equals_value_clause:
                  invocation_expression:
                    identifier:
                    argument_list:
                      argument:
                        identifier:
````

That is, `nameof()` is treated like a normal function. Should it be?  Is this intentional? :smile:
